### PR TITLE
Allow Increasing and Decreasing beyond cap

### PR DESCRIPTION
**Pull request by Nullctipus**
Also Removed unused namespaces

### CODE REVIEW

**Comment by Nullctipus** [comment]
[Debug.zip](https://github.com/HAWGT/GGST-COLOR-UNLOCKER/files/8810543/Debug.zip)
Here is a build of it

**Comment by HAWGT** [comment]
The offsets are wrong, the patterns for inc cap and dec cap are the same, that is going to give out the same address, from your exe alone, if I decremented the value, the game would straight up freeze, the game loops whenever you go from 10/11 to 79 or from 0 to 79, so I suspect it is something related to it, due to this being an external there's not much that can be done, maybe if we find a lot of NOPs or INT3 we could inject a bunch of code there and just call it.

Due to the the patterns being the exact same, you are only patching the increment cap.

**Comment by Nullctipus** [comment]
That's odd, it worked fine when I was coding it in c++ I must have transferred the code wrong 
```c++
#include <Psapi.h>
#include <TlHelp32.h>
#include <Windows.h>

void WriteToMemory(uintptr_t addressToWrite, char *valueToWrite)
{
	//used to change our file access type, stores the old
	//access type and restores it after the memory is written

	unsigned long OldProtection;
	//give that address read and write permissions and store the old permissions at oldProtection
	VirtualProtect((LPVOID)(addressToWrite), sizeof(valueToWrite), PAGE_EXECUTE_READWRITE, &OldProtection);
	//write the memory into the program and overwrite previous value
	// 
	WriteProcessMemory(GetCurrentProcess(), (LPVOID)addressToWrite, valueToWrite, sizeof(valueToWrite), nullptr);
	//memcpy((LPVOID)addressToWrite, valueToWrite, byteNum);

	//reset the permissions of the address back to oldProtection after writing memory
	VirtualProtect((LPVOID)(addressToWrite), sizeof(valueToWrite), OldProtection, NULL);
}
uintptr_t GetModuleBaseAddress(DWORD procId, const wchar_t *modName)
{
	uintptr_t modBaseAddr = 0;
	HANDLE hSnap = CreateToolhelp32Snapshot(TH32CS_SNAPMODULE | TH32CS_SNAPMODULE32, procId);
	if (hSnap != INVALID_HANDLE_VALUE)
	{
		MODULEENTRY32 modEntry;
		modEntry.dwSize = sizeof(modEntry);
		if (Module32First(hSnap, &modEntry))
		{
			do
			{
				if (!_wcsicmp(modEntry.szModule, modName))
				{
					modBaseAddr = (uintptr_t)modEntry.modBaseAddr;
					break;
				}
			} while (Module32Next(hSnap, &modEntry));
		}
	}
	CloseHandle(hSnap);
	return modBaseAddr;
}


uintptr_t baseAddr = GetModuleBaseAddress(GetCurrentProcessId(), L"GGST-Win64-Shipping.exe");
uintptr_t inc = baseAddr + 0xBFE855; //0x74, 0xD9
uintptr_t dec = baseAddr + 0xBFE8E9; //0x74, 0xD5
uintptr_t incCap = baseAddr + 0xBFE83F; //GGST-Win64-Shipping.exe+BFE83F - 7E 07                 - jle GGST-Win64-Shipping.exe+BFE848
uintptr_t decCap = baseAddr + 0xBFE8CF; 

uintptr_t PS1 = baseAddr + 0xC17D01;//0xE8, 0xBA, 0x97, 0xF7, 0xFF, 0x48, 0x63, 0x8B, 0x38, 0x04, 0x00, 0x00, 0x0F, 0xBE, 0x44, 0x08, 0x03
uintptr_t PS2 = baseAddr + 0xC0A6CE;//0x74, 0x24, 0x83, 0xBA, 0x3C, 0x04, 0x00, 0x00, 0x00, 0x74, 0x1B, 0xC7, 0x82, 0x3C, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
uintptr_t PSN = baseAddr + 0xEA55A4;//0x74, 0x08, 0x48, 0x8B, 0xCF, 0xE8, 0x02, 0x46, 0x25, 0x00, 0x0F, 0xB6, 0xC3

char IncCappatch[] = "\xEB\x07\x89\x58\x0C\x48\x8B\x45\x30\x8B\x50\x0C\x8B\x48\x08\xE8";
char DecCappatch[] = "\xEB\x0B\xC7\x40\x0C\x4F\x00\x00\x00\x48\x8B\x45\x30\x8B\x50\x0C\x8B\x48\x08";
char PSNpatch[] = "\x74\x08\x48\x8B\xCF\xE8\x02\x46\x25\x00\x90\x90\x90";
char PS1patch[] = "\xE8\xBA\x97\xF7\xFF\x48\x63\x8B\x38\x04\x00\x00\xB8\x59\x00\x00\x00";
char PS2patch[] = "\x74\x24\x83\xBA\x3C\x04\x00\x00\x00\x74\x1B\xC7\x82\x3C\x04\x00\x00\x59\x00\x00\x00";
char incpatch[] = "\x90\x90\x48\x8b\x4d\x30\x39\x71\x0c\x0f\x84";
char decpatch[] = "\x90\x90\x48\x8B\x4D\x30\x39\x71\x0C\x0F\x84";

BOOL APIENTRY DllMain(HMODULE hModule, DWORD fdwReason, LPVOID)
{
switch (fdwReason)
	{
		case DLL_PROCESS_ATTACH:
		{
			WriteToMemory(inc, incpatch);
			WriteToMemory(dec, decpatch);
			WriteToMemory(incCap, IncCappatch);
			WriteToMemory(decCap, DecCappatch);
			WriteToMemory(PSN, PSNpatch);
			WriteToMemory(PS1, PS1patch);
			WriteToMemory(PS2, PS2patch);
			break;
		}
	}
}
```

**Comment by Nullctipus** [comment]
OHH I see it now ill fix it up and see if it works... Tired me sucks

**Pull request closed without merging**
